// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/ru/spbau/mit/oquechy/stress/message.proto

package ru.spbau.mit.oquechy.stress;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stress.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 number = 1;</code>
     */
    java.util.List<java.lang.Integer> getNumberList();
    /**
     * <code>repeated int32 number = 1;</code>
     */
    int getNumberCount();
    /**
     * <code>repeated int32 number = 1;</code>
     */
    int getNumber(int index);
  }
  /**
   * Protobuf type {@code stress.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:stress.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                number_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              number_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                number_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                number_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          number_ = java.util.Collections.unmodifiableList(number_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.mit.oquechy.stress.MessageProto.internal_static_stress_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.mit.oquechy.stress.MessageProto.internal_static_stress_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.mit.oquechy.stress.MessageProto.Message.class, ru.spbau.mit.oquechy.stress.MessageProto.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> number_;
    /**
     * <code>repeated int32 number = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getNumberList() {
      return number_;
    }
    /**
     * <code>repeated int32 number = 1;</code>
     */
    public int getNumberCount() {
      return number_.size();
    }
    /**
     * <code>repeated int32 number = 1;</code>
     */
    public int getNumber(int index) {
      return number_.get(index);
    }

    private void initFields() {
      number_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < number_.size(); i++) {
        output.writeInt32(1, number_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < number_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(number_.get(i));
        }
        size += dataSize;
        size += 1 * getNumberList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.spbau.mit.oquechy.stress.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.spbau.mit.oquechy.stress.MessageProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stress.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stress.Message)
        ru.spbau.mit.oquechy.stress.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.mit.oquechy.stress.MessageProto.internal_static_stress_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.mit.oquechy.stress.MessageProto.internal_static_stress_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.mit.oquechy.stress.MessageProto.Message.class, ru.spbau.mit.oquechy.stress.MessageProto.Message.Builder.class);
      }

      // Construct using ru.spbau.mit.oquechy.stress.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        number_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.mit.oquechy.stress.MessageProto.internal_static_stress_Message_descriptor;
      }

      public ru.spbau.mit.oquechy.stress.MessageProto.Message getDefaultInstanceForType() {
        return ru.spbau.mit.oquechy.stress.MessageProto.Message.getDefaultInstance();
      }

      public ru.spbau.mit.oquechy.stress.MessageProto.Message build() {
        ru.spbau.mit.oquechy.stress.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.mit.oquechy.stress.MessageProto.Message buildPartial() {
        ru.spbau.mit.oquechy.stress.MessageProto.Message result = new ru.spbau.mit.oquechy.stress.MessageProto.Message(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          number_ = java.util.Collections.unmodifiableList(number_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.number_ = number_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.mit.oquechy.stress.MessageProto.Message) {
          return mergeFrom((ru.spbau.mit.oquechy.stress.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.mit.oquechy.stress.MessageProto.Message other) {
        if (other == ru.spbau.mit.oquechy.stress.MessageProto.Message.getDefaultInstance()) return this;
        if (!other.number_.isEmpty()) {
          if (number_.isEmpty()) {
            number_ = other.number_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNumberIsMutable();
            number_.addAll(other.number_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.mit.oquechy.stress.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.mit.oquechy.stress.MessageProto.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> number_ = java.util.Collections.emptyList();
      private void ensureNumberIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          number_ = new java.util.ArrayList<java.lang.Integer>(number_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getNumberList() {
        return java.util.Collections.unmodifiableList(number_);
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public int getNumberCount() {
        return number_.size();
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public int getNumber(int index) {
        return number_.get(index);
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public Builder setNumber(
          int index, int value) {
        ensureNumberIsMutable();
        number_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public Builder addNumber(int value) {
        ensureNumberIsMutable();
        number_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public Builder addAllNumber(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNumberIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, number_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 number = 1;</code>
       */
      public Builder clearNumber() {
        number_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:stress.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:stress.Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stress_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stress_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8main/resources/ru/spbau/mit/oquechy/st" +
      "ress/message.proto\022\006stress\"\031\n\007Message\022\016\n" +
      "\006number\030\001 \003(\005B+\n\033ru.spbau.mit.oquechy.st" +
      "ressB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stress_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stress_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stress_Message_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
