language: java

jdk:
  - oraclejdk9

os:
  - linux

before_script:
  - wget https://services.gradle.org/distributions/gradle-4.7-bin.zip
  - unzip gradle-4.7-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.7
  - export PATH=$GRADLE_HOME/bin:$PATH

script: 
  - chmod +x build.sh
  - bash build.sh
